### PR TITLE
Improve Java OSSRH pipeline with sonarqube publish and optional ws clean

### PR DESCRIPTION
**Pull request by Larusso**
## Description

This patch adds some improvements and fixes from the build gradle plugin pipeline. I fixed the default values for platform in the same way we fixed it for buildGradlePlugin in commit d88125bc. I also copied the setup for the sonarqube publish. As a last improvement I also added a new parameter `CLEAN_WORKSPACE` for both `buildGradlePlugin`, buildJavaLibraryOSSRH` and `buildWDKAutoSwitch`

The idea is to make the cleanup controlable during invocation of the pipeline. The default value is `true`.

Changes
=======

* ![FIX] `config.platform` default value lookup
* ![ADD] sonarqube publish setup in `buildJavaLibraryOSSRH`
* ![IMPROVE] cleanup workspace with pipeline parameter

[NEW]:      https://resources.atlas.wooga.com/icons/icon_new.svg "New"
[ADD]:      https://resources.atlas.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:  https://resources.atlas.wooga.com/icons/icon_improve.svg "Improve"
[CHANGE]:   https://resources.atlas.wooga.com/icons/icon_change.svg "Change"
[FIX]:      https://resources.atlas.wooga.com/icons/icon_fix.svg "Fix"
[UPDATE]:   https://resources.atlas.wooga.com/icons/icon_update.svg "Update"
[BREAK]:    https://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:   https://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]:      https://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS"
[ANDROID]:  https://resources.atlas.wooga.com/icons/icon_android.svg "Android"
[WEBGL]:    https://resources.atlas.wooga.com/icons/icon_webGL.svg "WebGL"
[GRADLE]:   https://resources.atlas.wooga.com/icons/icon_gradle.svg "GRADLE"
[UNITY]:    https://resources.atlas.wooga.com/icons/icon_unity.svg "Unity"
[LINUX]:    https://resources.atlas.wooga.com/icons/icon_linux.svg "Linux"
[WIN]:      https://resources.atlas.wooga.com/icons/icon_windows.svg "Windows"
[MACOS]:    https://resources.atlas.wooga.com/icons/icon_iOS.svg "macOS"

### CODE REVIEW

**Comment by Larusso** [comment]
@Joaquimmnetto how would I setup a test for these changes? Can this already be tested?

**Comment by Joaquimmnetto** [comment]
> @Joaquimmnetto how would I setup a test for these changes? Can this already be tested?
 Yeah, it is quite possible. You can mock the `clearWs` function and see if it is running or not when passing the `CLEAN_WORKSPACE` variable.

**Comment by Joaquimmnetto** [comment]
I'll salvage this and adapt to the new code struture. Putting my face on it so that I don't forget.

**Comment by Joaquimmnetto** [comment]
Closing this PR as it is redundant given the last months refactor and new features.

**Pull request closed without merging**
