### PR TITLE
[ATLAS-1886] Configurable Build Platform and Package Type

### PR DESCRIPTION
**Pull request by glebkobzar**
## Description
- Adding configurable package build platform and package type.
Now it is possible to specify platform (label) and package type in version:
```
unityVersions:
[
   [version: '2021.3.35f1', apiCompatibilityLevel: 'net_standard_2_0', label: 'linux', packageType: 'upm']
   ...
],
```
- Also making small refactoring of class names and moving parse code to UnityVersion class
Screenshot 2024-09-11 at 09 15 02
Screenshot 2024-09-11 at 09 14 46
Screenshot 2024-09-11 at 09 14 37

## JIRA Issue 
https://woogagmbh.atlassian.net/browse/ATLAS-1886

## Changes
* ![ADD] Adding configurable build platform and package type.

[NEW]:https://resources.atlas.wooga.com/icons/icon_new.svg "New"
[ADD]:https://resources.atlas.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:https://resources.atlas.wooga.com/icons/icon_improve.svg "IMPROVE"
[CHANGE]:https://resources.atlas.wooga.com/icons/icon_change.svg "Change"
[FIX]:https://resources.atlas.wooga.com/icons/icon_fix.svg "Fix"
[UPDATE]:https://resources.atlas.wooga.com/icons/icon_update.svg "Update"

[BREAK]:https://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:https://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]:https://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS"
[ANDROID]:https://resources.atlas.wooga.com/icons/icon_android.svg "Android"
[WEBGL]:https://resources.atlas.wooga.com/icons/icon_webGL.svg "WebGL"
[UNITY]:https://resources.atlas.wooga.com/icons/icon_unity.svg "Unity"
[GRADLE]:https://resources.atlas.wooga.com/icons/icon_gradle.svg "Gradle"
[LINUX]:https://resources.atlas.wooga.com/icons/icon_linux.svg "Linux"

### CODE REVIEW

**Review by pletoss — COMMENTED** [review]
Amazing! Thanks Gleb!

Kudos on super thorough PR in this new stack, including tests!


Just some small clarification requests:

1. i skimmed over the tests a bit, was there one that also covers that the initial setup step of paket is skipped ? 

2. Most importantly - does it still support / behave in the legacy wdkv2 exactly as before - as in it automatically adds linux and both package managers even if not declared ?

**Comment by glebkobzar** [comment]
> Amazing! Thanks Gleb!
> 
> Kudos on super thorough PR in this new stack, including tests!
> 
> Just some small clarification requests:
> 
> 1. i skimmed over the tests a bit, was there one that also covers that the initial setup step of paket is skipped ?
> 2. Most importantly - does it still support / behave in the legacy wdkv2 exactly as before - as in it automatically adds linux and both package managers even if not declared ?

1. Not a problem, Will add to WDKCheckSpec, which I found already after making a PR. I would anyway have to change/split it for number 2
2. I we really want to keep V2 working, I would better modify buildUnityWdkV2 to add linux steps, rather than creating a WDKConfigV3, WDKConfigSpecV3 and WDKCheckSpecV3. Linux step added in WDKConfig implicitly and all tests with *2 in WDKCheckSpec looked too hacky to me anyway. At least I want to try.

**Comment by glebkobzar** [comment]
1. To test that setup for paket and upm was completed or skipped I check if there is a respective stash in BuildUnityWdkV3Spec file.
2. I added support for BuildUnityWdkV2 extending WDKConfig a bit and just one additional parameter in BuildUnityWdkV2. I also added tests for different count and sets of extraLabels

**Review by pletoss — APPROVED** [review]
lgtm. 

were you able to do an integration test, including the backwards-compatibility on an actual wdk ? (this should be quite easy by referring to the "optional_platforms" in the Jenkinsfile of that WDK

**Comment by glebkobzar** [comment]
Test done checked V2 and V3 also second time. Second time upm package was published without any delay
Screenshot 2024-09-26 at 12 00 27

**Pull request merged**
